app_login/urls.py
from django.urls import path
from app_login.views import login_view, logout_view

app_name = 'login'

urlpatterns = [
    path('', login_view, name="login_view"),
    path('login/', logout_view, name="logout_view"),
]

project/urls.py
from random import random
from django.http import HttpResponse
from django.contrib import admin
from django.urls import path, include
from app_datetime import views
from app_weather.views import weather_view
from store.views import products_view


def random_view(request):
    if request.method == 'GET':
        data = random()
        return HttpResponse(data)


urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
    path('random/', random_view),
    path('datetime/', views.datetime_view),
    path('weather/', include('app_weather.urls')),
    path('login/', include('app_login.urls')),
    path('wishlist/', include('wishlist.urls')),
]

store/urls.py
from django.urls import path
from .views import products_view, shop_view, products_page_view, cart_view, cart_add_view, cart_del_view, coupon_check_view, delivery_estimate_view, cart_buy_now_view, cart_remove_view

app_name = 'store'

urlpatterns = [
    path('product/', products_view),
    path('', shop_view, name="shop_view"),
    path('product/<slug:page>.html', products_page_view, name="products_page_view"),
    path('product/<int:page>', products_page_view),
    path('cart/', cart_view, name="cart_view"),
    path('cart/add/<str:id_product>', cart_add_view),
    path('cart/del/<str:id_product>', cart_del_view),
    path('coupon/check/<slug:name_coupon>', coupon_check_view),
    path('delivery/estimate', delivery_estimate_view),
    path('cart/buy/<str:id_product>', cart_buy_now_view, name="buy_now"),
    path('cart/remove/<str:id_product>', cart_remove_view, name="remove_now"),
]

wishlist/urls.py
from django.urls import path
from .views import wishlist_view, wishlist_add_json, wishlist_del_json, wishlist_json, remove_from_wishlist, wishlist_remove_view


app_name = 'wishlist'

urlpatterns = [
    path('', wishlist_view, name='wishlist_view'),
    path('api/add/<str:id_product>', wishlist_add_json),
    path('api/del/<str:id_product>', wishlist_del_json, name='wishlist_del_json'),
    path('api/', wishlist_json),
    path('remove/<str:id_product>', wishlist_remove_view, name='remove_from_wishlist_now'),
    ]

store/models.py
from django.db import models

DATABASE = {'1': {'name': 'Болгарский перец',
                  'discount': 30,
                  'price_before': 300.00,
                  'price_after': 210.00,
                  'description': 'Сочный и яркий, он добавит красок и вкуса в ваши блюда.',
                  'rating': 4.9,
                  'review': 250,
                  'sold_value': 600,
                  'weight_in_stock': 500,
                  'category': 'Овощи',
                  'id': 1,
                  'url': 'store/images/product-1.jpg',
                  'html': 'bell_pepper'
                  },
            '2': {'name': 'Клубника',
                  'discount': None,
                  'price_before': 500.00,
                  'price_after': 500.00,
                  'description': 'Сладкая и ароматная клубника, полная витаминов, чтобы сделать ваш день ярче.',
                  'rating': 5.0,
                  'review': 200,
                  'sold_value': 700,
                  'weight_in_stock': 400,
                  'category': 'Фрукты',
                  'id': 2,
                  'url': 'store/images/product-2.jpg',
                  'html': 'strawberry'
                  },
            '3': {'name': 'Стручковая фасоль',
                  'discount': None,
                  'price_before': 250.00,
                  'price_after': 250.00,
                  'rating': 4.8,
                  'review': 250,
                  'sold_value': 500,
                  'weight_in_stock': 500,
                  'description': 'Зеленая натуральность и богатство белка для вашей здоровой диеты.',
                  'rating': 5.0,
                  'review': 100,
                  'sold_value': 500,
                  'weight_in_stock': 600,
                  'category': 'Овощи',
                  'id': 3,
                  'url': 'store/images/product-3.jpg',
                  'html': 'green_beans'
                  },
            '4': {'name': 'Краснокочанная капуста',
                  'discount': None,
                  'price_before': 90.00,
                  'price_after': 90.00,
                  'description': 'Удивите своих гостей экзотическим вкусом и цветом ваших блюд.',
                  'rating': 4.7,
                  'review': 30,
                  'sold_value': 50,
                  'weight_in_stock': 300,
                  'category': 'Овощи',
                  'id': 4,
                  'url': 'store/images/product-4.jpg',
                  'html': 'purple_cabbage'
                  },
            '5': {'name': 'Помидоры',
                  'discount': 25,
                  'price_before': 240.00,
                  'price_after': 180.00,
                  'description': 'Свежие и сочные помидоры для идеальных салатов и соусов.',
                  'rating': 4.9,
                  'review': 350,
                  'sold_value': 700,
                  'weight_in_stock': 300,
                  'category': 'Овощи',
                  'id': 5,
                  'url': 'store/images/product-5.jpg',
                  'html': 'tomatoes'
                  },
            '6': {'name': 'Брокколи',
                  'discount': None,
                  'price_before': 320.00,
                  'price_after': 320.00,
                  'description': 'Здоровье в каждом кусочке, чтобы укрепить вашу иммунную систему.',
                  'rating': 4.9,
                  'review': 150,
                  'sold_value': 250,
                  'weight_in_stock': 300,
                  'category': 'Овощи',
                  'id': 6,
                  'url': 'store/images/product-6.jpg',
                  'html': 'broccoli'
                  },
            '7': {'name': 'Морковь',
                  'discount': None,
                  'price_before': 50.00,
                  'price_after': 50.00,
                  'description': 'Красота и здоровье для ваших глаз и кожи в каждой моркови.',
                  'rating': 4.8,
                  'review': 220,
                  'sold_value': 800,
                  'weight_in_stock': 900,
                  'category': 'Овощи',
                  'id': 7,
                  'url': 'store/images/product-7.jpg',
                  'html': 'carrots'
                  },
            '8': {'name': 'Фруктовый сок',
                  'discount': None,
                  'price_before': 120.00,
                  'price_after': 120.00,
                  'description': 'Натуральная свежесть и энергия в каждом глотке.',
                  'rating': 4.9,
                  'review': 300,
                  'sold_value': 800,
                  'weight_in_stock': 1200,
                  'category': 'Соки',
                  'id': 8,
                  'url': 'store/images/product-8.jpg',
                  'html': 'fruit_juice'
                  },
            '9': {'name': 'Лук',
                  'discount': 20,
                  'price_before': 40.00,
                  'price_after': 32.00,
                  'description': 'Придайте особый аромат и вкус вашим блюдам с нашим свежим луком.',
                  'rating': 4.6,
                  'review': 80,
                  'sold_value': 170,
                  'weight_in_stock': 350,
                  'category': 'Овощи',
                  'id': 9,
                  'url': 'store/images/product-9.jpg',
                  'html': 'onion'
                  },
            '10': {'name': 'Яблоки',
                   'discount': None,
                   'price_before': 130.00,
                   'price_after': 130.00,
                   'description': 'Сочные и сладкие яблоки - идеальная закуска для здорового перекуса.',
                   'rating': 4.7,
                   'review': 30,
                   'sold_value': 70,
                   'weight_in_stock': 200,
                   'category': 'Фрукты',
                   'id': 10,
                   'url': 'store/images/product-10.jpg',
                   'html': 'apple'
                   },
            '11': {'name': 'Чеснок',
                   'discount': None,
                   'price_before': 150.00,
                   'price_after': 150.00,
                   'description': 'Секрет вкусных блюд и поддержания здоровья вашего сердца.',
                   'rating': 4.9,
                   'review': 150,
                   'sold_value': 400,
                   'weight_in_stock': 1000,
                   'category': 'Овощи',
                   'id': 11,
                   'url': 'store/images/product-11.jpg',
                   'html': 'garlic'
                   },
            '12': {'name': 'Перец Чили',
                   'discount': None,
                   'price_before': 400.00,
                   'price_after': 400.00,
                   'description': 'Острая страсть для тех, кто ищет приключения на своей тарелке.',
                   'rating': 5.0,
                   'review': 40,
                   'sold_value': 300,
                   'weight_in_stock': 50,
                   'category': 'Овощи',
                   'id': 12,
                   'url': 'store/images/product-12.jpg',
                   'html': 'chilli'
                   },
            }

store/views.py
from django.contrib.auth import get_user
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, HttpRequest, HttpResponseNotFound
from .models import DATABASE
from logic.services import filtering_category, view_in_cart, add_to_cart, remove_from_cart
from django.contrib.auth.decorators import login_required


def products_view(request):
    if request.method == "GET":
        # Обработка id из параметров запроса (уже было реализовано ранее)
        if id_product := request.GET.get("id"):
            if data := DATABASE.get(id_product):
                return JsonResponse(data, json_dumps_params={'ensure_ascii': False,
                                                             'indent': 4})
            return HttpResponseNotFound("Данного продукта нет в базе данных")

        # Обработка фильтрации из параметров запроса
        category_key = request.GET.get("category")  # Считали 'category'
        if ordering_key := request.GET.get("ordering"): # Если в параметрах есть 'ordering'
            if request.GET.get("reverse") in ('true', 'True'): # Если в параметрах есть 'ordering' и 'reverse'=True
                data = filtering_category(DATABASE, category_key, ordering_key, reverse=True) #  Провести фильтрацию с параметрами
            else:
                data = filtering_category(DATABASE, category_key, ordering_key) #  Провести фильтрацию с параметрами
        else:
            data = filtering_category(DATABASE, category_key) #  Провести фильтрацию с параметрами
        # В этот раз добавляем параметр safe=False, для корректного отображения списка в JSON
        return JsonResponse(data, safe=False, json_dumps_params={'ensure_ascii': False, 'indent': 4})


def shop_view(request: HttpRequest):
    if request.method == "GET":
        category_key = request.GET.get("category")
        if ordering_key := request.GET.get("ordering"):
            if request.GET.get("reverse") in ('true', 'True'):
                data = filtering_category(DATABASE, category_key, ordering_key, True)
            else:
                data = filtering_category(DATABASE, category_key, ordering_key)
        else:
            data = filtering_category(DATABASE, category_key)
        return render(request, 'store/shop.html', context={"products": data, "category": category_key})


'''def products_page_view(request, page):
    if request.method == "GET":
        if isinstance(page, str):
            for data in DATABASE.values():
                if data['html'] == page:  # Если значение переданного параметра совпадает именем html файла
                    with open(f'store/products/{page}.html', encoding='utf-8') as page:
                        data = page.read()
                    return HttpResponse(data)
        elif isinstance(page, int):
            data = DATABASE.get(str(page))
            if data:
                with open(f"store/products/{data['html']}.html", encoding='utf-8') as page:
                    res = page.read()
                return HttpResponse(res)

        return HttpResponse(status=404)'''


def products_page_view(request, page):
    if request.method == "GET":
        if isinstance(page, str):
            for data in DATABASE.values():
                if data['html'] == page:
                    return render(request, "store/product.html", context={"product": data})

        elif isinstance(page, int):
            # Обрабатываем условие того, что пытаемся получить страницу товара по его id
            data = DATABASE.get(str(page))  # Получаем какой странице соответствует данный id
            if data:
                return render(request, "store/product.html", context={"product": data})

        return HttpResponse(status=404)


@login_required(login_url='login:login_view')
def cart_view(request):
    if request.method == "GET":
        current_user = get_user(request).username
        data = view_in_cart(request)[current_user]
        if request.GET.get('format') == 'JSON':
            return JsonResponse(data, json_dumps_params={'ensure_ascii': False, 'indent': 4})

        products = []
        for product_id, quantity in data['products'].items():
            product = DATABASE[product_id]
            product['quantity'] = quantity
            product['price_total'] = f'{quantity * product["price_after"]:.2f}'
            products.append(product)

        return render(request, 'store/cart.html', context={'products': products})


@login_required(login_url='login:login_view')
def cart_add_view(request, id_product):
    if request.method == "GET":
        result = add_to_cart(request, id_product)
        if result:
            return JsonResponse({"answer": "Продукт успешно добавлен в корзину"},
                                json_dumps_params={'ensure_ascii': False})

        return JsonResponse({"answer": "Неудачное добавление в корзину"},
                            status=404, json_dumps_params={'ensure_ascii': False})


def cart_del_view(request, id_product):
    if request.method == "GET":
        result = remove_from_cart(request, id_product)
        if result:
            return JsonResponse({"answer": "Продукт успешно удалён из корзины"},
                                json_dumps_params={'ensure_ascii': False})

        return JsonResponse({"answer": "Неудачное удаление из корзины"},
                            status=404, json_dumps_params={'ensure_ascii': False})


def coupon_check_view(request, name_coupon):

    DATA_COUPON = {
        "coupon": {
            "value": 10,
            "is_valid": True},
        "coupon_old": {
            "value": 20,
            "is_valid": False},
    }

    if request.method == "GET":
        if name_coupon in DATA_COUPON:
            data = {"discount": DATA_COUPON[name_coupon]["value"], "is_valid": DATA_COUPON[name_coupon]["is_valid"]}
            return JsonResponse(data, json_dumps_params={'ensure_ascii': False})

    return HttpResponseNotFound("Неверный купон")


def delivery_estimate_view(request):
    DATA_PRICE = {
        "Россия": {
            "Москва": {"price": 80},
            "Санкт-Петербург": {"price": 80},
            "fix_price": 100,
        },
    }
    if request.method == "GET":
        data = request.GET
        country = data.get('country')
        city = data.get('city')
        if city in DATA_PRICE[country]:
            return JsonResponse(DATA_PRICE[country][city], json_dumps_params={'ensure_ascii': False})
        elif city not in DATA_PRICE[country]:
            return JsonResponse({"price": DATA_PRICE[country]["fix_price"]}, json_dumps_params={'ensure_ascii': False})

    return HttpResponseNotFound("Неверные данные")


@login_required(login_url='login:login_view')
def cart_buy_now_view(request, id_product):
    if request.method == "GET":
        result = add_to_cart(request, id_product)
        if result:
            return redirect("store:cart_view")

        return HttpResponseNotFound("Неудачное добавление в корзину")


def cart_remove_view(request, id_product):
    if request.method == "GET":
        result = remove_from_cart(request, id_product)  # Вызвать функцию удаления из корзины
        if result:
            return redirect("store:cart_view")  # Вернуть перенаправление на корзину

        return HttpResponseNotFound("Неудачное удаление из корзины")

store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %} <!-- Блок для названия страницы-->

    {% endblock %}

    {% block head %} <!-- Блок ссылок в head-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">

	<link type="image/x-icon" href="{% static 'store/images/favicon.png' %}" rel="shortcut icon">
    <link rel="stylesheet" href="{% static 'store/css/open-ionic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'store/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'store/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'store/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'store/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'store/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'store/css/style.css' %}">
    {% endblock %}
</head>
<body class="goto-here">
    {% block header %} <!-- Блок для header страницы с данными магазина-->
    <div class="py-1 bg-primary">
		<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">+ 7 (812) 123 45 678</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">mystore@email.ru</span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
						    <span class="text">Доставка в течении 3-5 рабочих дней. Бесплатный возврат</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
    {% endblock %}

    {% block nav %} <!-- Блок для навигационной панели страницы магазина-->
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="#">Vegefoods</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Навигация
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item"><a href="{% url 'store:shop_view'%}" class="nav-link">Магазин</a>
			  <li class="nav-item"><a href="{% url 'wishlist:wishlist_view'%}" class="nav-link">Избранное</a>
			  <li class="nav-item"><a href="{% url 'store:cart_view'%}" class="nav-link">Корзина</a>
			  {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'login:logout_view'%}" class="nav-link">Выйти из аккаунта</a>
                    <li class="nav-item"><a class="nav-link">Привет {{user.username}}!</a>
                {% else %}
                    <li class="nav-item"><a href="{% url 'login:login_view'%}" class="nav-link">Войти в аккаунт</a>
                {% endif %}
	        </ul>
	      </div>
	    </div>
	  </nav>
    {% endblock %}

    {% block content %} <!-- Блок для уникального содержимого страницы-->

    {% endblock %}

    {% block news %} <!-- Блок для новостной панели-->
    <section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Подпишись на новости</h2>
          	<span>Получайте по электронной почте обновления о наших последних магазинах и специальных предложениях</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Введите ваш email">
                <input type="submit" value="Подписаться" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    {% endblock %}

    {% block footer %} <!-- Блок для нижней панели страницы-->
    <footer class="ftco-footer ftco-section">
      <div class="container">
      	<div class="row">
      		<div class="mouse">
						<a href="#" class="mouse-icon">
							<div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
						</a>
					</div>
      	</div>
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vegefoods</h2>
              <p><i>Зеленый выбор для здоровой жизни!</i></p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-telegram"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-vk"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-whatsapp"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Навигация</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Магазин</a></li>
                <li><a href="#" class="py-2 d-block">О нас</a></li>
                <li><a href="#" class="py-2 d-block">Блог</a></li>
                <li><a href="#" class="py-2 d-block">Связаться с нами</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Помощь</h2>
              <div class="d-flex">
	              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
	                <li><a href="#" class="py-2 d-block">Информация о доставке</a></li>
	                <li><a href="#" class="py-2 d-block">Возврат и Обмен</a></li>
	                <li><a href="#" class="py-2 d-block">Условия и Положения</a></li>
	                <li><a href="#" class="py-2 d-block">Политика конфиденциальности</a></li>
	              </ul>
	              <ul class="list-unstyled">
	                <li><a href="#" class="py-2 d-block">Вопрос - ответ</a></li>
	                <li><a href="#" class="py-2 d-block">Контакты</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Остались вопросы?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">Россия, г. Санкт-Петербург, ул. Ответов на вопросы, д.1</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+ 7 (812) 123 45 678</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.ru</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Авторские права &copy;<script>document.write(new Date().getFullYear());</script> Все права защищены | Этот шаблон сделан с <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
          </div>
        </div>
      </div>
    </footer>
    {% endblock %}

    {% block scripts %} <!-- Блок для загрузки javascript страницы-->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

    <script src="{% static 'store/js/jquery.min.js' %}"></script>
  	<script src="{% static 'store/js/jquery-migrate-3.0.1.min.js' %}"></script>
  	<script src="{% static 'store/js/popper.min.js' %}"></script>
  	<script src="{% static 'store/js/bootstrap.min.js' %}"></script>
  	<script src="{% static 'store/js/jquery.easing.1.3.js' %}"></script>
  	<script src="{% static 'store/js/jquery.waypoints.min.js' %}"></script>
  	<script src="{% static 'store/js/jquery.stellar.min.js' %}"></script>
  	<script src="{% static 'store/js/owl.carousel.min.js' %}"></script>
  	<script src="{% static 'store/js/jquery.magnific-popup.min.js' %}"></script>
  	<script src="{% static 'store/js/aos.js' %}"></script>
  	<script src="{% static 'store/js/jquery.animateNumber.min.js' %}"></script>
  	<script src="{% static 'store/js/bootstrap-datepicker.js' %}"></script>
  	<script src="{% static 'store/js/scrollax.min.js' %}"></script>
  	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  	<script src="{% static 'store/js/google-map.js' %}"></script>
  	<script src="{% static 'store/js/main.js' %}"></script>
    {% endblock %}

    {% block custom_scripts %}  <!-- Блок для загрузки дополнительного кода встроенного в html-->

    {% endblock %}
</body>
</html>