project/urls.py
from random import random
from django.http import HttpResponse
from django.contrib import admin
from django.urls import path, include
from app_datetime import views
from app_weather.views import weather_view
from store.views import products_view


def random_view(request):
    if request.method == 'GET':
        data = random()
        return HttpResponse(data)


urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
    path('random/', random_view),
    path('datetime/', views.datetime_view),
    path('weather/', include('app_weather.urls')),
    path('login/', include('app_login.urls')),
    path('wishlist/', include('wishlist.urls')),
]

store/urls.py
from django.urls import path
from .views import products_view, shop_view, products_page_view, cart_view, cart_add_view, cart_del_view, coupon_check_view, delivery_estimate_view, cart_buy_now_view, cart_remove_view

app_name = 'store'

urlpatterns = [
    path('product/', products_view),
    path('', shop_view, name="shop_view"),
    path('product/<slug:page>.html', products_page_view, name="products_page_view"),
    path('product/<int:page>', products_page_view),
    path('cart/', cart_view, name="cart_view"),
    path('cart/add/<str:id_product>', cart_add_view),
    path('cart/del/<str:id_product>', cart_del_view),
    path('coupon/check/<slug:name_coupon>', coupon_check_view),
    path('delivery/estimate', delivery_estimate_view),
    path('cart/buy/<str:id_product>', cart_buy_now_view, name="buy_now"),
    path('cart/remove/<str:id_product>', cart_remove_view, name="remove_now"),
]

wishlist/urls.py
from django.urls import path
from .views import wishlist_view, wishlist_add_json, wishlist_del_json, wishlist_json, remove_from_wishlist, wishlist_remove_view


app_name = 'wishlist'

urlpatterns = [
    path('', wishlist_view, name='wishlist_view'),
    path('api/add/<str:id_product>', wishlist_add_json),
    path('api/del/<str:id_product>', wishlist_del_json, name='wishlist_del_json'),
    path('api/', wishlist_json),
    path('remove/<str:id_product>', wishlist_remove_view, name='remove_from_wishlist_now'),
    ]

wishlist/models.py
from django.db import models

# Create your models here.

wishlist/views.py
from django.shortcuts import render, redirect
from logic.services import view_in_wishlist, add_to_wishlist, remove_from_wishlist
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse, HttpRequest, HttpResponseNotFound


@login_required(login_url='login:login_view')
def wishlist_view(request):
    if request.method == "GET":
        current_user = get_user(request).username
        data = view_in_wishlist(request)        # wishlist = {user: {'products': []}}

        products = data[current_user]['products']

        return render(request, 'wishlist/wishlist.html', context={"products": products})


@login_required(login_url='login:login_view')
def wishlist_json(request):
    """
    Просмотр всех продуктов в избранном для пользователя и возвращение этого в JSON
    """
    if request.method == "GET":
        current_user = get_user(request).username
        data = view_in_wishlist(request)
        if data:
            return JsonResponse(data, json_dumps_params={'ensure_ascii': False})

        return JsonResponse({"answer": 'Пользователь не авторизован.'}, status=404, json_dumps_params={'ensure_ascii': False})


@login_required(login_url='login:login_view')
def wishlist_add_json(request, id_product: str):
    if request.method == "GET":
        result = add_to_wishlist(request, id_product)
        if result:
            return JsonResponse({"answer": "Продукт успешно добавлен в избранное"},
                                json_dumps_params={'ensure_ascii': False})

        return JsonResponse({"answer": "Неудачное добавление в избранное"}, status=404, json_dumps_params={'ensure_ascii': False})


def wishlist_del_json(request, id_product: str):
    if request.method == "GET":
        result = remove_from_wishlist(request, id_product)
        if result:
            return JsonResponse({"answer": "Продукт успешно удалён из избранного"},
                                json_dumps_params={'ensure_ascii': False})

        return JsonResponse({"answer": "Неудачное удаление из избранного"},
                            status=404, json_dumps_params={'ensure_ascii': False})


def wishlist_remove_view(request, id_product):
    if request.method == "GET":
        result = remove_from_wishlist(request, id_product)  # Вызвать функцию удаления из избранного
        if result:
            return redirect("wishlist:wishlist_view")  # Вернуть перенаправление в избранное

        return HttpResponseNotFound("Неудачное удаление из избранного")

wishlist/templates/wishlist/wishlist.html
{% extends 'store/base.html' %}
{%load static%}

{% block title %}
<title>Избранное</title>
{% endblock %}

{% block content%}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'store/images/bg_1.jpg' %});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs"><span class="mr-2"></span></p>
            <h1 class="mb-0 bread">Избранное</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
      <div class="container">
        <div class="row">
          <div class="col-md-12 ftco-animate">
            <div class="cart-list">
              <table class="table">
                <thead class="thead-primary">
                <tr class="text-center">
                  <th>&nbsp;</th>
                  <th>&nbsp;</th>
                  <th>Продукт</th>
                  <th>Цена, &#x20bd</th>
                </tr>
                </thead>
                <tbody>
                  {% for product in products %}
                  {% for id, prod in product.items %}
                    <tr class="text-center">
                      <td class="product-remove"><a href="{% url 'wishlist:remove_from_wishlist_now' prod.id %}"><span class="ion-ios-close"></span></a></td>

                      <td class="image-prod"><div class="img" style="background-image:url({% static prod.url %});"></div></td>

                      <td class="product-name">
                        <h3>{{prod.name}}</h3>
                        <p>{{prod.description}}</p>
                      </td>
                      {% if prod.discount %}
                      <td class="price">{{prod.price_after}}</td>
                      {% else %}
                      <td class="price">{{prod.price_before}}</td>
                      {% endif %}
                    </tr><!-- END TR-->
                  {% endfor %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}